### PR TITLE
Revert "Revert "Don't use threads in this test""

### PR DESCRIPTION
**Pull request by untitaker**
This reverts commit 1577e1386e737eca69dbb6cfe6b8bf979f7b2944.

### CODE REVIEW

**Comment by untitaker** [comment]
I have no idea why this fails, I thought it'd be a fairly straightforward change. Anybody?

**Comment by davidism** [comment]
What's the history/status of this?  Why did it need to be reverted?  Did those other two referenced issues effect it?

**Comment by untitaker** [comment]
It's a refactor that I thought was completely trivial, but for some reason it breaks CI, so I postponed it indefinetly.

On 31 October 2015 04:55:55 CET, David Lord <notifications@github.com> wrote:
>What's the history/status of this?  Why did it need to be reverted? 
>Did those other two referenced issues effect it?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/mitsuhiko/flask/pull/1407#issuecomment-152690469

-- 
Sent from my phone. Please excuse my brevity.

**Comment by untitaker** [comment]
I don't care about this anymore. IIRC either variant is fine, so who really cares?

**Pull request closed without merging**
