### PR TITLE
Add datetime.date support to JSONEncoder

### PR DESCRIPTION
**Pull request by RealSalmon**
Add support for the datetime.date type to jsonify, which currently only supports the datetime.datetime type.

##### Changelog
1. datetime.date type support in flask.json.jsonify

### CODE REVIEW

**Comment by davidism** [comment]
`datetime` is a subclass of `date`, there's no need to check both.  Simply `isinstance(o, date)` will suffice.

**Comment by RealSalmon** [comment]
@davidism - thanks! I've reduced it to a single check.

**Comment by davidism** [comment]
You should add a test for this as well.  In addition, the commits can be squashed into one.

**Comment by untitaker** [comment]
*And* please add a changelog too :)

You can squash commits with:

    git rebase -i master

@davidism Thanks for reviewing this!

**Comment by RealSalmon** [comment]
Will do, thanks!

**Comment by RealSalmon** [comment]
Added tests for both datetime.datetime and datetime.date types.

**Comment by untitaker** [comment]
Could you add a changelog item for 1.0 too?

**Comment by RonnyPfannschmidt** [comment]
why does the "unit-test" involve a flask app and a test client, its just jsonify this time 
(i realize the surrounding tests are acceptance tests of request handling)

**Comment by RealSalmon** [comment]
@untitaker - changelog entry added. sorry - I misunderstood what you were asking for before.

@RonnyPfannschmidt - mainly it's that way because that's how all of other tests are to be set up, but also because jsonify doesn't seem to work outside of an application context. I supposed because it returns an actual response in addition to the serialized data.

**Comment by untitaker** [comment]
Woo, thanks!

Your explanation for using a temporary app for testing is sound, although I haven't explored this myself.

**Pull request merged**
