### PR TITLE
Fix pep8 with logging

### PR DESCRIPTION
**Pull request by andyxning**
This should make the logging module more pep8 compatible. This PR fix problem issued in #1440 .

I made this PR to update first argument of class method in logging module from `x` to `self` in **master** branch. However, i can not make sure if i should at the same time make a PR to also clean the `logging` module in **0.10-maintenance**.

BTW, is the maintenance branch read-only(i checked out that last commit in **0.10-maintenance** is about years ago)? If so, what is the difference between a tag and this maintenance branch.

### CODE REVIEW

**Comment by untitaker** [comment]
Please remove that merge commit with `git rebasew -i master`.

**Comment by andyxning** [comment]
Sorry for not skilled git knowledge. I think i make things more bad than beginning. I think i should close this PR and issue another one with correct commit.

**Comment by ThiefMaster** [comment]
No, simply force-push to the same branch. Pull requests are always between branches.

**Comment by untitaker** [comment]
Ok, run that command again and force-push to the same branch... don't pull to resolve conflicts.

**Comment by andyxning** [comment]
@ThiefMaster  Thanks very much for the advice and it finally worked correctly. A new skill has been leaned. :)

**Comment by untitaker** [comment]
Great, thanks!

**Pull request merged**
