### PR TITLE
Skip tests if redbaron is not installed

### PR DESCRIPTION
**Pull request by redian**
This will make sure these tests will be skipped if you don't have redbaron installed.

### CODE REVIEW

**Comment by ThiefMaster** [comment]
unrelated, but your `user.email` is set to an email not associated with your github account

**Comment by redian** [comment]
@ThiefMaster i noticed that as well, i just updated my profile and added the other email (work) address.

**Comment by ThiefMaster** [comment]
Works great! In the end it's a skip and not an xfail, so I'd change the commit message accordingly

btw, usually a separate branch is better for PRs - since PRs are often merged with a merge commit and not a fast-forward your `master` will diverge from upstream's master once the PR is merged (which is easy to fix though, once it's merged you can simply `git fetch upstream` and `git reset --hard upstream/master` and then force-push)

**Comment by redian** [comment]
Thanks for your suggestions @ThiefMaster 
For my other commits i will use a new branch from my fork not master,
and will fetch upstream.
Regards

**Comment by redian** [comment]
Sorry about that, i did not realise that i was pushing over here.

**Comment by davidism** [comment]
Rebase to remove the last two commits and I'll merge this.

**Comment by redian** [comment]
Hi @davidism i removed the last 2 commits sorry about that.

**Pull request merged**
