### PR TITLE
Done

### PR DESCRIPTION
**Pull request by AlexKhodaverdian**
Added a Q & A to a README from information found throughout the web

### CODE REVIEW

**Comment by untitaker** [comment]
I think this information is better stored somewhere else than the README.

**Comment by AlexKhodaverdian** [comment]
Do you mind if I ask where a more appropriate place would be for this?

**Comment by davidism** [comment]
A post on your personal blog, as this is almost entirely opinion.  Also, there are a bunch of spelling and grammar mistakes, and some of the answers seem to be cut short.

**Comment by ThiefMaster** [comment]
Besides that, "Done" is not a very good title for a pull request...

**Pull request closed without merging**
