### PR TITLE
make hostname configurable

### PR DESCRIPTION
**Pull request by ferstar**
make hostname configurable if it defined in the ``SERVER_NAME`` config

### CODE REVIEW

**Comment by untitaker** [comment]
Why?

You can do this yourself, after all you're the one calling `app.run`.

**Comment by ferstar** [comment]
Yes, but maybe it would be convenient to read config from the configuration file :-)

**Comment by ThiefMaster** [comment]
Why, it's just for the dev server anyway, you rarely want to run it on anything but localhost

**Comment by ferstar** [comment]
@ThiefMaster Of course, I was actually tested on my own , and this `patch` is very simple.

**Comment by untitaker** [comment]
I'm against this. There are infinite ways to fetch/compute the values for `host` and `port`, and all of them can already be computed before launching `app.run`.

**Comment by ferstar** [comment]
@untitaker Got, Thank you for your explanation and I will change it myself. BTW, happy weekend! :+1:

**Comment by untitaker** [comment]
Thanks for your understanding, and a happy weekend to you too. :)

**Pull request closed without merging**
