### PR TITLE
Added flake8 for checking Python syntax

### LINKED ISSUE #1561: add automatic pep8 test in travis
It's very useful and easy to modify travis.yml。

### PR DESCRIPTION
**Pull request by Akasurde**
Fixes #1561 
Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

### CODE REVIEW

**Comment by ThiefMaster** [comment]
I don't think this PR is worth merging unless it also includes a commit that:

- configures flake8 in a sane way (e.g. don't complain about unused imports in `__init__.py` and ignore anything outside the `flask` package)
- fixes all problems

**Comment by ThiefMaster** [comment]
Using `before_script` doesn't even run the tests if flake8 fails. I don't think this is a good idea. Especially for pull requests it's not very helpful if failing style checks skip the unit tests.

**Comment by ThiefMaster** [comment]
Would it make sense to run flake8 from tox.ini?

[pytest-pep8](https://pypi.python.org/pypi/pytest-pep8) could also be an option

**Comment by Akasurde** [comment]
OK. Let me try flake8 from tox.ini

**Comment by Akasurde** [comment]
@ThiefMaster How we are going to handle existing pep8 errors?

**Comment by zoidbergwill** [comment]
Fixing them all might be the easiest option, with `# noqa`s where they make sense.

@ThiefMaster recommending fixing them all [here](https://github.com/mitsuhiko/flask/pull/1585#issuecomment-149191309)

**Comment by adrianmoisey** [comment]
Another option is to pass `--exit-zero` to `flake8` for now, until all the issues can get cleaned up

**Comment by davidism** [comment]
continued in #1702

**Pull request closed without merging**
