### PR TITLE
Melvinflask

### PR DESCRIPTION
**Pull request by melvin0008**
Added www.minurl.in example to flask/examples

### CODE REVIEW

**Comment by untitaker** [comment]
Hello @melvin0008, thanks for your contribution!

Unfortunately this example is way too big to be included into Flask, especially as it has its own license and multiple images. I recommend putting this in a separate repository.

**Comment by melvin0008** [comment]
Okay sure. Thanks.
What if I removed the license?

**Comment by untitaker** [comment]
It's still to big IMO. We're planning to introduce some sort of list for community-provided complete apps in the future, so stay tuned!

**Comment by melvin0008** [comment]
Sure Thank You.

**Pull request closed without merging**
