### PR TITLE
Purpose readme contribution

### PR DESCRIPTION
**Pull request by strtw**
To make Flask more approachable to a larger number of users—from informed developers to curious passersby and new and interested visitors—I have added a new section to the technologyRepo README and created this file in .md format. The section is entitled What to Use Flask for and When to Use It. As the name suggests, the new section attempts to explain in plain and straightforward language what Flask is used for and when one should use it.

Other repositories may begin to use this new informative section soon, as my colleagues contact open-source technologies in an effort to make them more accessible to the many new users learning to code and GitHub every day.

Thank you for your consideration, I look forward to hearing your response.

### CODE REVIEW

**Comment by davidism** [comment]
This doesn't feel like a significant improvement to me, and some of the new information is either inaccurate or just opinion.  The readme is fine how it is.

**Comment by strtw** [comment]
Thanks David,

I appreciate the response. This was part of a school assignment to
understand GitHub but also to attempt to provide a general overview section
for the curious or novice to programming. I did my best to take accurate
information I gleaned from the official documents as well as Armin
Ronacher's interview about the framework
<https://talkpython.fm/episodes/show/13/flask-web-framework-and-much-much-more>
on Talk Python to me. It was not my intention to introduce opinion or
inaccurate information.

Do you think there would be value to having such a contribution, if the
inaccurate / opinion information could be taken out?

I'm sure the readme is fine for some segments of people, but do you think
that it could be improved to enhance comprehension for a wider audience?
I'm not sure if gaining a wider audience is one of the project's interests
so I'd be interested in hearing your thoughts as one of the projects core
contributors.

Best regards,
Stu

**Comment by ThiefMaster** [comment]
In my opinion having a slim README and more details in the docs is more useful (as it's already the case)

**Comment by ThiefMaster** [comment]
Is this also from the same school assignment btw? https://github.com/mitsuhiko/flask/pull/1720

**Comment by strtw** [comment]
It looks like it might be... We have different assignments.  Thanks.

**Comment by ThiefMaster** [comment]
Out of curiosity, was sending pull requests to projects part of the assignment? While contributing to projects is great, making it a school assignment seems like a great way to cause low-quality PRs...

**Pull request closed without merging**
