### PR TITLE
Add line of code required to run examples for Other Testing Tricks section

### PR DESCRIPTION
**Pull request by KWinston**
As it stated, documentation states full example that demonstrates this approach, with the way it is implemented. It requires this line of code to perform the test functions on the three examples under Other Testing Tricks.

### CODE REVIEW

**Comment by keyanp** [comment]
Hi @KWinston, in the future it would be helpful make your PR title more specific and clear. The commit message you have is much less ambiguous and would be a good PR title as well.

To address the suggested change, it is meant to be implied that the code provided in that subsection is part of the same module defined above in the "The Testing Skeleton" subsection. Therefore an import statement is not necessary. Notice how the sample code in the "Logging In and Out" and "The First Test" sections similarly does not include import statements.

**Comment by KWinston** [comment]
Okay, I will keep note of that. In this case, import flask is not in "The Testing Skeleton" either meaning this section of code will not be able to run without import flask.
Should it be in "The Testing Skeleton"?

Other lines such as in Faking Resources and Context has
from flask import appcontext_pushed
which allow it to use appcontext_pushed.function()
instead of flask.appcontext_pushed.function()

There is a differences of expressions in the snippets.

**Comment by untitaker** [comment]
I think this is fine as-is. The testing skeleton covers a specific example, the code blocks there are completely distinct.

**Comment by untitaker** [comment]
Thanks!

**Pull request merged**
