### PR TITLE
Abh ocean

### PR DESCRIPTION
**Pull request by ABaldwinHunter**
testing

### CODE REVIEW

**Comment by ThiefMaster** [comment]
Goddamnit, like everyone else doing that: It is highly inappropriate to dump :hankey: like this PR into repos of real projects, especially if they are not your projects!

**Comment by timofurrer** [comment]
You seriously did **32** commits for **12** additions in **2** files? Really?

**Comment by untitaker** [comment]
https://twitter.com/sigmavirus24/status/660085913595154432

**Comment by joostdevries** [comment]
Looking at [this](https://github.com/ABaldwinHunter), I'm reasonably sure this happened by accident. Not entirely sure though...

**Comment by mitsuhiko** [comment]
There is no need to drag this out further.

**Comment by untitaker** [comment]
This is kind-of late, but still.

@ThiefMaster Usually I apprechiate your direct communication methods when reviewing half-assed pull requests. This isn't the case here. It's obvious that the author is new to GitHub. Why did your response to a honest mistake have to be so hostile?

**Pull request closed without merging**
