### PR TITLE
In case a test fails a .cache directory is created

### PR DESCRIPTION
**Pull request by redian**
I think this could be handy and potentially minimise the risk
anyone commits it to the project.

```
flask - (master) $ tree .cache/
.cache/
└── v
    └── cache
        └── lastfailed

```

### CODE REVIEW

**Comment by ThiefMaster** [comment]
I think it's a new feature in a somewhat recent pytest version to create `.cache` - having it on `.gitignore` makes sense indeed.

I'd add `.cache/` though to make it clear that it's a directory and possibly reword the commit message - right now it sounds more like the commit changes it so that such a directory is created. *"Add .cache dir to gitignore"* might summarize the commit better?

**Comment by mitsuhiko** [comment]
+1 on the gitignore. I saw this pop up in other projects of mine as well recently.

**Comment by redian** [comment]
I missed your renaming bit sorry, will close this pull request and make another one.

Sorry about that.

**Comment by ThiefMaster** [comment]
you can just forcepush to the branch; no need to create a new PR

**Pull request closed without merging**
